name: cide pipeline
on: 
  push: 
   branches:
    - main

jobs: 
 test-enviromnent:
  runs-on: ubuntu-latest

  steps:
    - name: Check out repo code
      uses: actions/checkout@v4
    - name: Run a dignosi script
      run: echo "hello neel cicd is run sucessfully" 
